AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Parses AWS GD events and pushes dynamic address objects to FortiGates

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Environmental variables for Lambda function execution
      Parameters:
      - IPAddrObjPrefix
      - FQDNAddrObjPrefix
      - AddrGrpPrefix
      - PlaceholderAddrObjName
      - AggregateAddrGrpName
      - AddrGrpBatchCreate
      - FortiGateLoginInfoList
      - FortiosRestAPItimeout
      - FortiosRestAPIdebug
    - Label:
        default: KMS Key information for encyrpting environmental variables
      Parameters:
      - KeyAdministrator

Parameters:
  IPAddrObjPrefix:
    Description: 'Provide a short prefix to append to the dynamic IPv4 based address objects used by the FortiGate.  Here is an example object if you use the default value (gdIp-1.2.3.4/32)'
    Type: String
    Default: gdIp-
  FQDNAddrObjPrefix:
    Description: 'Provide a short prefix to append to the dynamic FQDN based address objects used by the FortiGate.  Here is an example object if you use the default value (gdDns-www.baddns.com)'
    Type: String
    Default: gdDns-
  AddrGrpPrefix:
    Description: 'Provide a short prefix to append to the dynamic address group objects used by the FortiGate.  Here is an example object if you use the default value (gdGrp-UnauthorizedAccessEC2-SSHBruteForce)'
    Type: String
    Default: gdGrp-
  PlaceholderAddrObjName:
    Description: 'Provide a name for the place holder address object which will be used when creating dynamic address groups used by the FortiGate.  Here is an example object if you use the default value (gdGrp-AggregateEvents)'
    Type: String
    Default: gd-placeholder
  AggregateAddrGrpName:
    Description: 'Provide a name for the dynamic aggregate address group which will contain all other dynamic address group objects used by the FortiGate.  Here is an example object if you use the default value (gdGrp-AggregateEvents)'
    Type: String
    Default: gdGrp-AggregateEvents
  AddrGrpBatchCreate:
    Type: String
    Description: 'Select on if you want all known dynamic address group objects to be checked and created if they do not exist, each time the lambda function is triggered.  Select off to have the dynamic address group objects created only when a matching Guard Duty event type is seen.'
    Default: 'on'
    AllowedValues:
    - 'on'
    - 'off'
  FortiGateLoginInfoList:
    Description: 'Provide a list of one or many FortiGate IP, admin account, and password in a comma delimited list format with a pipe sign used between each set of FortiGate entires.  (ie 1.1.1.1,admin,passwd|2.2.2.2,otheradmin,i-123456abcdef)'
    NoEcho: 'true'
    Type: String
    Default: 1.1.1.1,admin,passwd|2.2.2.2,otheradmin,i-abcdef
  FortiosRestAPItimeout:
    Type: String
    Description: 'Specify the timeout value in seconds for the FortiOS REST API calls'
    Default: 10
  FortiosRestAPIdebug:
    Type: String
    Description: 'Select the debug level for the FortiOS REST API calls (Extremely Verbose)'
    Default: 'off'
    AllowedValues:
    - 'on'
    - 'off'
  KeyAdministrator:
    Description: 'Provide the AWS username for your account to manage the KMS key created by the template'
    Type: String
    Default: johndoe

Mappings: 
  CodeRegionMap: 
    ap-northeast-1: 
      LambdaCode: fortibucket-ap-northeast-1
    ap-northeast-2: 
      LambdaCode: fortibucket-ap-northeast-2
    ap-south-1: 
      LambdaCode: fortibucket-ap-south-1
    ap-southeast-1: 
      LambdaCode: fortibucket-ap-southeast-1
    ap-southeast-2: 
      LambdaCode: fortibucket-ap-southeast-2
    ca-central-1: 
      LambdaCode: fortibucket-ca-central-1
    eu-central-1: 
      LambdaCode: fortibucket-eu-central-1
    eu-west-1: 
      LambdaCode: fortibucket-eu-west-1
    eu-west-2: 
      LambdaCode: fortibucket-eu-west-2
    eu-west-3: 
      LambdaCode: fortibucket-eu-west-3
    sa-east-1: 
      LambdaCode: fortibucket-sa-east-1
    us-east-1: 
      LambdaCode: fortibucket-us-east-1
    us-east-2: 
      LambdaCode: fortibucket-us-east-2
    us-west-1: 
      LambdaCode: fortibucket-us-west-1
    us-west-2: 
      LambdaCode: fortibucket-us-west-2

Resources:
  LambdaKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName:
        Fn::Join:
          - ''
          - - 'alias/'
            - Ref: AWS::StackName
            - '-LambdaFunctionKey'
      TargetKeyId:
        Ref: LambdaKmsKey

  LambdaKmsKey: 
    Type: "AWS::KMS::Key"
    Properties: 
      Description: "KMS CMK for encrypting Lambda function environment variables"
      KeyPolicy: 
        Version: "2012-10-17"
        Id: "LambdaKmsKey-GuardDutyFunction"
        Statement: 
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal: 
              AWS:
                Fn::Join:
                - ''
                - - 'arn:aws:iam::'
                  - Ref: AWS::AccountId
                  - ':root'
            Action: kms:*
            Resource: "*"
          - Sid: "Allow access for Key Administrators"
            Effect: "Allow"
            Principal: 
              AWS:
                - Fn::Join:
                  - ''
                  - - 'arn:aws:iam::'
                    - Ref: AWS::AccountId
                    - ':root'
                - Fn::Join:
                  - ''
                  - - 'arn:aws:iam::'
                    - Ref: AWS::AccountId
                    - ':user/'
                    - Ref: KeyAdministrator
            Action: 
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:TagResource"
              - "kms:UntagResource"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
          - Sid: "Allow use of the key"
            Effect: "Allow"
            Principal: 
              AWS:
                - Fn::Join:
                  - ''
                  - - 'arn:aws:iam::'
                    - Ref: AWS::AccountId
                    - ':root'
                - Fn::Join:
                  - ''
                  - - 'arn:aws:iam::'
                    - Ref: AWS::AccountId
                    - ':user/'
                    - Ref: KeyAdministrator
                - !GetAtt LambdaFunctionRole.Arn
            Action: 
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
          - Sid: "Allow attachment of persistent resources"
            Effect: Allow
            Principal:
              AWS:
                - Fn::Join:
                  - ''
                  - - 'arn:aws:iam::'
                    - Ref: AWS::AccountId
                    - ':user/'
                    - Ref: KeyAdministrator
                - !GetAtt LambdaFunctionRole.Arn
            Action:
            - kms:CreateGrant
            - kms:ListGrants
            - kms:RevokeGrant
            Resource: "*"
            Condition:
              Bool:
                kms:GrantIsForAWSResource: 'true'

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  LambdaFunctionPolicy:
    DependsOn:
    - LambdaFunctionRole
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaFunctionPolicy
      Roles: 
        - Ref: LambdaFunctionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface
          Resource:
          - "*"

  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: aws-gd-fgt.lambda_handler
      Runtime: python2.7
      CodeUri: 
        Bucket: !FindInMap [CodeRegionMap, !Ref 'AWS::Region', LambdaCode]
        Key: aws-gd-fgt-lambda.zip
      Description: Parses AWS GD events and pushes dynamic address objects to FortiGates
      MemorySize: 128
      Timeout: 300
      Role: !GetAtt LambdaFunctionRole.Arn
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - GuardDuty Finding
              source:
                - aws.guardduty
      Environment:
        Variables:
          addripPREFIX: !Ref IPAddrObjPrefix
          addrfqdnPREFIX: !Ref FQDNAddrObjPrefix
          addrgrpPREFIX: !Ref AddrGrpPrefix
          placeholderaddrNAME: !Ref PlaceholderAddrObjName
          aggaddrgrpNAME: !Ref AggregateAddrGrpName
          addrgrpBATCHcreate: !Ref AddrGrpBatchCreate
          fgtLOGINinfo: !Ref FortiGateLoginInfoList
          fgtapiTIMEOUT: !Ref FortiosRestAPItimeout
          fgtapiDEBUG: !Ref FortiosRestAPIdebug
